version: '3'
services:
  game-score-api:
    restart: on-failure
    build: ./app
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
      - ~/.m2:/root/.m2
    command: mvn clean spring-boot:run