spring:
  application:
    name: score-api
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/game
    username: admin
    password: admin
  jpa:
    hibernate.ddl-auto: validate
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: jdbc:mysql://127.0.0.1:3306/game
    user: admin
    password: admin

metrics:
  default-tags:
    service: ${spring.application.name}
    serviceVersion: @project.version@

management:
  health:
    elasticsearch:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,prometheus,loggers,caches
  server:
    port: 8088