spring:
  application:
    name: score-api
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:gamedb
    driverClassName: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
    username: sa
    password: test
  jpa:
    hibernate.ddl-auto: none
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
  flyway:
    schemas: PUBLIC
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: jdbc:h2:mem:gamedb;DB_CLOSE_DELAY=-1
    user: sa
    password: test